import 'package:assignment_cse3212/model/contact.dart';
List<Contact> contactList = [
  Contact(
    id: '1',
    name: 'Lutfozzaman Babar',
    phoneNumber: '+8801712345678',
    email: 'Babar@example.com',
    address: '123 Dhaka Rd, Dhaka, Bangladesh',
    imagePath: 'assets/images/q.jpg',
  ),
  Contact(
    id: '4',
    name: 'Sheikh Hasina',
    phoneNumber: '+8801712345681',
    email: 'hasina@example.com',
    address: '321 Khulna St, Khulna, Bangladesh',
    imagePath: 'assets/images/h.jpg',
  ),
  Contact(
    id: '2',
    name: 'Ziaur Rahman',
    phoneNumber: '+8801712345679',
    email: 'ziaur@example.com',
    address: '456 Sylhet St, Sylhet, Bangladesh',
    imagePath: 'assets/images/z.jpg',
  ),
  Contact(
    id: '3',
    name: 'Khaleda Zia',
    phoneNumber: '+8801712345680',
    email: 'khaleda@example.com',
    address: '789 Chittagong Ave, Chittagong, Bangladesh',
    imagePath: 'assets/images/k.jpg',
  ),

  Contact(
    id: '5',
    name: 'Hussain Muhammad Ershad',
    phoneNumber: '+8801712345682',
    email: 'ershad@example.com',
    address: '654 Barisal Rd, Barisal, Bangladesh',
    imagePath: 'assets/images/e.jpg',
  ),
  Contact(
    id: '6',
    name: 'Abul Maal Abdul Muhith',
    phoneNumber: '+8801712345683',
    email: 'muhith@example.com',
    address: '987 Rajshahi Rd, Rajshahi, Bangladesh',
    imagePath: 'assets/images/6.jpg',
  ),
  Contact(
    id: '7',
    name: 'Mohammad Nasim',
    phoneNumber: '+8801712345684',
    email: 'nasim@example.com',
    address: '159 Rangpur St, Rangpur, Bangladesh',
    imagePath: 'assets/images/7.jpg',
  ),
  Contact(
    id: '8',
    name: 'Jatiya Party Leader Manna',
    phoneNumber: '+8801712345685',
    email: 'manna@example.com',
    address: '753 Bogura Rd, Bogura, Bangladesh',
    imagePath: 'assets/images/8.jpg',
  ),
  Contact(
    id: '9',
    name: 'Mirza Fakhrul Islam Alamgir',
    phoneNumber: '+8801712345686',
    email: 'fakhrul@example.com',
    address: '852 Comilla Rd, Comilla, Bangladesh',
    imagePath: 'assets/images/9.jpg',
  ),
  Contact(
    id: '10',
    name: 'Saifur Rahman',
    phoneNumber: '+8801712345687',
    email: 'saifur@example.com',
    address: '369 Mymensingh St, Mymensingh, Bangladesh',
    imagePath: 'assets/images/10.jpg',
  ),
  Contact(
    id: '11',
    name: 'Rashid Khan Menon',
    phoneNumber: '+8801712345688',
    email: 'rashid@example.com',
    address: '147 Pabna St, Pabna, Bangladesh',
    imagePath: 'assets/images/11.jpg',
  ),
  Contact(
    id: '12',
    name: 'Tarique Rahman',
    phoneNumber: '+8801712345689',
    email: 'tarique@example.com',
    address: '258 Faridpur Rd, Faridpur, Bangladesh',
    imagePath: 'assets/images/12.jpg',
  ),
  Contact(
    id: '13',
    name: 'A.B.M. Mohiuddin Chowdhury',
    phoneNumber: '+8801712345690',
    email: 'mohiuddin@example.com',
    address: '369 Tangail Rd, Tangail, Bangladesh',
    imagePath: 'assets/images/13.jpg',
  ),
  Contact(
    id: '14',
    name: 'Khalid Mahmood Chowdhury',
    phoneNumber: '+8801712345691',
    email: 'khalid@example.com',
    address: '123 Naogaon Rd, Naogaon, Bangladesh',
    imagePath: 'assets/images/14.jpg',
  ),
];

